# DataQ Example Configuration

plugins:
  - id: filescan
    enabled: false
    binary_path: "../cmd/plugins/filescan/bin/filescan.exe"
    config:
      root_path: "./data"
      include_patterns: "*.txt,*.pdf,*.doc*"  # Fixed: single string with comma-separated patterns
      exclude_patterns: "*.tmp,~$*"           # Fixed: single string with comma-separated patterns

  # Gmail plugin configuration
  - id: gmail
    enabled: true
    binary_path: "../cmd/plugins/gmail/bin/gmail.exe"
    config:
      credentials_path: "./credentials.json"  # Credentials in example dir
      token_path: "./token.json"             # Token in example dir
