# DataQ Example Configuration

plugins:
  - id: filescan
    enabled: false  # Disable filescan for now
    config:
      root_path: "./data"  # Directory to scan
      include_patterns:
        - "*.txt"
        - "*.pdf"
        - "*.doc*"
      exclude_patterns:
        - "*.tmp"
        - "~$*"

  # Gmail plugin configuration
  - id: gmail
    enabled: true
    config:
      credentials_path: "./credentials.json"  # Credentials in example dir
      token_path: "./token.json"             # Token in example dir
