# DataQ Example Configuration

plugins:
  - id: filescan
    enabled: true
    config:
      root_path: "./data"  # Directory to scan
      include_patterns:
        - "*.txt"
        - "*.pdf"
        - "*.doc*"
      exclude_patterns:
        - "*.tmp"
        - "~$*"

  # Example Gmail plugin configuration
  - id: gmail
    enabled: false  # Set to true after configuring credentials
    config:
      credentials_json: |
        {
          "installed": {
            "client_id": "YOUR_CLIENT_ID",
            "client_secret": "YOUR_CLIENT_SECRET",
            "redirect_uris": ["http://localhost:8085"]
          }
        }
      token_json: |
        {
          "access_token": "YOUR_ACCESS_TOKEN",
          "token_type": "Bearer",
          "refresh_token": "YOUR_REFRESH_TOKEN",
          "expiry": "2024-01-01T00:00:00Z"
        }
